application: ibdstockfinder
version: 1
runtime: python
api_version: 1

inbound_services:
- xmpp_message

handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /css
  static_dir: css
  
- url: /watching
  script: main.py
  
- url: /check_alerts
  script: main.py
  login: admin

- url: /.*
  script: main.py
  login: required
